package coolify

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ApplicationsService handles communication with the application-related endpoints of the Coolify API.
type ApplicationsService struct {
	client *Client
}

// ListApplicationsOptions specifies optional parameters for listing applications.
type ListApplicationsOptions struct {
	Tag string `url:"tag,omitempty"`
}

// List retrieves all applications.
func (s *ApplicationsService) List(ctx context.Context, opts ...ListApplicationsOptions) ([]Application, error) {
	path := "applications"
	if len(opts) > 0 && opts[0].Tag != "" {
		path = fmt.Sprintf("applications?tag=%s", url.QueryEscape(opts[0].Tag))
	}

	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return nil, err
	}

	var apps []Application
	_, err = s.client.do(ctx, req, &apps)
	return apps, err
}

// Get retrieves a specific application by its UUID.
func (s *ApplicationsService) Get(ctx context.Context, uuid string) (*Application, error) {
	path := fmt.Sprintf("applications/%s", uuid)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return nil, err
	}

	app := new(Application)
	_, err = s.client.do(ctx, req, app)
	return app, err
}

// CreatePublicRequest defines the parameters for creating a public repository application.
type CreatePublicRequest struct {
	ProjectUUID          string  `json:"project_uuid"`
	ServerUUID           string  `json:"server_uuid"`
	EnvironmentName      string  `json:"environment_name"`
	EnvironmentUUID      string  `json:"environment_uuid"`
	GitRepository        string  `json:"git_repository"`
	GitBranch            string  `json:"git_branch"`
	BuildPack            string  `json:"build_pack"`
	PortsExposes         string  `json:"ports_exposes"`
	DestinationUUID      *string `json:"destination_uuid,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Description          *string `json:"description,omitempty"`
	Domains              *string `json:"domains,omitempty"`
	GitCommitSHA         *string `json:"git_commit_sha,omitempty"`
	IsStatic             *bool   `json:"is_static,omitempty"`
	IsSPA                *bool   `json:"is_spa,omitempty"`
	IsAutoDeployEnabled  *bool   `json:"is_auto_deploy_enabled,omitempty"`
	IsForceHTTPSEnabled  *bool   `json:"is_force_https_enabled,omitempty"`
	InstallCommand       *string `json:"install_command,omitempty"`
	BuildCommand         *string `json:"build_command,omitempty"`
	StartCommand         *string `json:"start_command,omitempty"`
	BaseDirectory        *string `json:"base_directory,omitempty"`
	PublishDirectory     *string `json:"publish_directory,omitempty"`
	InstantDeploy        *bool   `json:"instant_deploy,omitempty"`
	ForceDomainOverride  *bool   `json:"force_domain_override,omitempty"`
	AutogenerateDomain   *bool   `json:"autogenerate_domain,omitempty"`
}

// CreateResponse defines the standard response for resource creation.
type CreateResponse struct {
	UUID string `json:"uuid"`
}

// CreatePublic creates a new application based on a public Git repository.
func (s *ApplicationsService) CreatePublic(ctx context.Context, reqBody CreatePublicRequest) (*CreateResponse, error) {
	req, err := s.client.newRequest(http.MethodPost, "applications/public", reqBody)
	if err != nil {
		return nil, err
	}

	resp := new(CreateResponse)
	_, err = s.client.do(ctx, req, resp)
	return resp, err
}

// CreatePrivateGHAppRequest defines the parameters for creating a private repository application through a GitHub App.
type CreatePrivateGHAppRequest struct {
	ProjectUUID          string  `json:"project_uuid"`
	ServerUUID           string  `json:"server_uuid"`
	EnvironmentName      string  `json:"environment_name"`
	EnvironmentUUID      string  `json:"environment_uuid"`
	GitHubAppUUID        string  `json:"github_app_uuid"`
	GitRepository        string  `json:"git_repository"`
	GitBranch            string  `json:"git_branch"`
	BuildPack            string  `json:"build_pack"`
	PortsExposes         string  `json:"ports_exposes"`
	DestinationUUID      *string `json:"destination_uuid,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Description          *string `json:"description,omitempty"`
	Domains              *string `json:"domains,omitempty"`
	GitCommitSHA         *string `json:"git_commit_sha,omitempty"`
	IsStatic             *bool   `json:"is_static,omitempty"`
	IsSPA                *bool   `json:"is_spa,omitempty"`
	IsAutoDeployEnabled  *bool   `json:"is_auto_deploy_enabled,omitempty"`
	IsForceHTTPSEnabled  *bool   `json:"is_force_https_enabled,omitempty"`
	InstallCommand       *string `json:"install_command,omitempty"`
	BuildCommand         *string `json:"build_command,omitempty"`
	StartCommand         *string `json:"start_command,omitempty"`
	BaseDirectory        *string `json:"base_directory,omitempty"`
	PublishDirectory     *string `json:"publish_directory,omitempty"`
	InstantDeploy        *bool   `json:"instant_deploy,omitempty"`
	ForceDomainOverride  *bool   `json:"force_domain_override,omitempty"`
	AutogenerateDomain   *bool   `json:"autogenerate_domain,omitempty"`
}

// CreatePrivateGHApp creates a new application based on a private repository via GitHub App.
func (s *ApplicationsService) CreatePrivateGHApp(ctx context.Context, reqBody CreatePrivateGHAppRequest) (*CreateResponse, error) {
	req, err := s.client.newRequest(http.MethodPost, "applications/private-github-app", reqBody)
	if err != nil {
		return nil, err
	}

	resp := new(CreateResponse)
	_, err = s.client.do(ctx, req, resp)
	return resp, err
}

// CreatePrivateDeployKeyRequest defines the parameters for creating a private repository application through a Deploy Key.
type CreatePrivateDeployKeyRequest struct {
	ProjectUUID          string  `json:"project_uuid"`
	ServerUUID           string  `json:"server_uuid"`
	EnvironmentName      string  `json:"environment_name"`
	EnvironmentUUID      string  `json:"environment_uuid"`
	PrivateKeyUUID       string  `json:"private_key_uuid"`
	GitRepository        string  `json:"git_repository"`
	GitBranch            string  `json:"git_branch"`
	BuildPack            string  `json:"build_pack"`
	PortsExposes         string  `json:"ports_exposes"`
	DestinationUUID      *string `json:"destination_uuid,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Description          *string `json:"description,omitempty"`
	Domains              *string `json:"domains,omitempty"`
	GitCommitSHA         *string `json:"git_commit_sha,omitempty"`
	IsStatic             *bool   `json:"is_static,omitempty"`
	IsSPA                *bool   `json:"is_spa,omitempty"`
	IsAutoDeployEnabled  *bool   `json:"is_auto_deploy_enabled,omitempty"`
	IsForceHTTPSEnabled  *bool   `json:"is_force_https_enabled,omitempty"`
	InstallCommand       *string `json:"install_command,omitempty"`
	BuildCommand         *string `json:"build_command,omitempty"`
	StartCommand         *string `json:"start_command,omitempty"`
	BaseDirectory        *string `json:"base_directory,omitempty"`
	PublishDirectory     *string `json:"publish_directory,omitempty"`
	InstantDeploy        *bool   `json:"instant_deploy,omitempty"`
	ForceDomainOverride  *bool   `json:"force_domain_override,omitempty"`
	AutogenerateDomain   *bool   `json:"autogenerate_domain,omitempty"`
}

// CreatePrivateDeployKey creates a new application based on a private repository via Deploy Key.
func (s *ApplicationsService) CreatePrivateDeployKey(ctx context.Context, reqBody CreatePrivateDeployKeyRequest) (*CreateResponse, error) {
	req, err := s.client.newRequest(http.MethodPost, "applications/private-deploy-key", reqBody)
	if err != nil {
		return nil, err
	}

	resp := new(CreateResponse)
	_, err = s.client.do(ctx, req, resp)
	return resp, err
}

// CreateDockerfileRequest defines parameters for creating an application based on a raw Dockerfile.
type CreateDockerfileRequest struct {
	ProjectUUID          string  `json:"project_uuid"`
	ServerUUID           string  `json:"server_uuid"`
	EnvironmentName      string  `json:"environment_name"`
	EnvironmentUUID      string  `json:"environment_uuid"`
	Dockerfile           string  `json:"dockerfile"`
	PortsExposes         *string `json:"ports_exposes,omitempty"`
	DestinationUUID      *string `json:"destination_uuid,omitempty"`
	Name                 *string `json:"name,omitempty"`
	Description          *string `json:"description,omitempty"`
	Domains              *string `json:"domains,omitempty"`
	InstantDeploy        *bool   `json:"instant_deploy,omitempty"`
	ForceDomainOverride  *bool   `json:"force_domain_override,omitempty"`
	AutogenerateDomain   *bool   `json:"autogenerate_domain,omitempty"`
}

// CreateDockerfile creates a new application based on a raw Dockerfile (without Git).
func (s *ApplicationsService) CreateDockerfile(ctx context.Context, reqBody CreateDockerfileRequest) (*CreateResponse, error) {
	req, err := s.client.newRequest(http.MethodPost, "applications/dockerfile", reqBody)
	if err != nil {
		return nil, err
	}

	resp := new(CreateResponse)
	_, err = s.client.do(ctx, req, resp)
	return resp, err
}

// CreateDockerImageRequest defines parameters for creating an application from an existing Docker registry image.
type CreateDockerImageRequest struct {
	ProjectUUID             string  `json:"project_uuid"`
	ServerUUID              string  `json:"server_uuid"`
	EnvironmentName         string  `json:"environment_name"`
	EnvironmentUUID         string  `json:"environment_uuid"`
	DockerRegistryImageName string  `json:"docker_registry_image_name"`
	DockerRegistryImageTag  string  `json:"docker_registry_image_tag"`
	PortsExposes            *string `json:"ports_exposes,omitempty"`
	DestinationUUID         *string `json:"destination_uuid,omitempty"`
	Name                    *string `json:"name,omitempty"`
	Description             *string `json:"description,omitempty"`
	Domains                 *string `json:"domains,omitempty"`
	LimitsCPUs              *string `json:"limits_cpus,omitempty"`
	LimitsMemory            *string `json:"limits_memory,omitempty"`
	CustomDockerRunOptions  *string `json:"custom_docker_run_options,omitempty"`
	InstantDeploy           *bool   `json:"instant_deploy,omitempty"`
	ForceDomainOverride     *bool   `json:"force_domain_override,omitempty"`
	AutogenerateDomain      *bool   `json:"autogenerate_domain,omitempty"`
}

// CreateDockerImage creates a new application based on an existing Docker Registry Image (without Git).
func (s *ApplicationsService) CreateDockerImage(ctx context.Context, reqBody CreateDockerImageRequest) (*CreateResponse, error) {
	req, err := s.client.newRequest(http.MethodPost, "applications/dockerimage", reqBody)
	if err != nil {
		return nil, err
	}

	resp := new(CreateResponse)
	_, err = s.client.do(ctx, req, resp)
	return resp, err
}

// Delete deletes a specific application.
// If stopAndRemove is true, the query param `delete_configurations=true` is sent (standard Coolify teardown behaviour).
func (s *ApplicationsService) Delete(ctx context.Context, uuid string, stopAndRemove bool) error {
	path := fmt.Sprintf("applications/%s", uuid)
	if stopAndRemove {
		path = fmt.Sprintf("%s?delete_configurations=true", path)
	}

	req, err := s.client.newRequest(http.MethodDelete, path, nil)
	if err != nil {
		return err
	}

	_, err = s.client.do(ctx, req, nil)
	return err
}

// LogsOptions specifies options when fetching application logs.
type LogsOptions struct {
	Lines int `url:"lines,omitempty"`
}

// GetLogs retrieves live or cached logs for the application container.
func (s *ApplicationsService) GetLogs(ctx context.Context, uuid string, opts ...LogsOptions) (string, error) {
	path := fmt.Sprintf("applications/%s/logs", uuid)
	if len(opts) > 0 && opts[0].Lines > 0 {
		path = fmt.Sprintf("%s?lines=%d", path, opts[0].Lines)
	}

	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return "", err
	}

	var logs string
	_, err = s.client.do(ctx, req, &logs)
	return logs, err
}

// Start triggers container deployment and start.
func (s *ApplicationsService) Start(ctx context.Context, uuid string) (string, error) {
	path := fmt.Sprintf("applications/%s/start", uuid)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return "", err
	}

	var message string
	_, err = s.client.do(ctx, req, &message)
	return message, err
}

// Stop halts the application container.
func (s *ApplicationsService) Stop(ctx context.Context, uuid string) error {
	path := fmt.Sprintf("applications/%s/stop", uuid)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return err
	}

	_, err = s.client.do(ctx, req, nil)
	return err
}

// Restart restarts the application.
func (s *ApplicationsService) Restart(ctx context.Context, uuid string) (string, error) {
	path := fmt.Sprintf("applications/%s/restart", uuid)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return "", err
	}

	var message string
	_, err = s.client.do(ctx, req, &message)
	return message, err
}

// CreateEnvRequest represents parameters to create a new environment variable.
type CreateEnvRequest struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	IsPreview   bool   `json:"is_preview"`
	IsLiteral   bool   `json:"is_literal"`
	IsMultiline bool   `json:"is_multiline"`
	IsShownOnce bool   `json:"is_shown_once"`
}

// CreateEnvResponse represents the response when an env variable is created.
type CreateEnvResponse struct {
	UUID string `json:"uuid"`
}

// CreateEnv creates a new environment variable for an application.
func (s *ApplicationsService) CreateEnv(ctx context.Context, uuid string, reqBody CreateEnvRequest) (*CreateEnvResponse, error) {
	path := fmt.Sprintf("applications/%s/envs", uuid)
	req, err := s.client.newRequest(http.MethodPost, path, reqBody)
	if err != nil {
		return nil, err
	}

	resp := new(CreateEnvResponse)
	_, err = s.client.do(ctx, req, resp)
	return resp, err
}

// ListEnvs retrieves all environment variables for the application.
func (s *ApplicationsService) ListEnvs(ctx context.Context, uuid string) ([]EnvironmentVariable, error) {
	path := fmt.Sprintf("applications/%s/envs", uuid)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return nil, err
	}

	var envs []EnvironmentVariable
	_, err = s.client.do(ctx, req, &envs)
	return envs, err
}

// EnvBulkUpdateRequest defines environment variables bulk updates.
type EnvBulkUpdateRequest struct {
	Envs []EnvironmentVariable `json:"envs"`
}

// BulkUpdateEnvs updates environment variables in bulk.
func (s *ApplicationsService) BulkUpdateEnvs(ctx context.Context, uuid string, envs []EnvironmentVariable) error {
	path := fmt.Sprintf("applications/%s/envs/bulk", uuid)
	req, err := s.client.newRequest(http.MethodPost, path, EnvBulkUpdateRequest{Envs: envs})
	if err != nil {
		return err
	}

	_, err = s.client.do(ctx, req, nil)
	return err
}

// UpdateEnvRequest represents parameters to create or update an environment variable.
type UpdateEnvRequest struct {
	Key         string `json:"key"`
	Value       string `json:"value"`
	IsLiteral   bool   `json:"is_literal"`
	IsMultiline bool   `json:"is_multiline"`
	IsPreview   bool   `json:"is_preview"`
	IsRuntime   bool   `json:"is_runtime"`
	IsBuildtime bool   `json:"is_buildtime"`
}

// UpdateEnv creates or updates a specific environment variable for an application.
func (s *ApplicationsService) UpdateEnv(ctx context.Context, uuid string, reqBody UpdateEnvRequest) (*EnvironmentVariable, error) {
	path := fmt.Sprintf("applications/%s/envs", uuid)
	req, err := s.client.newRequest(http.MethodPatch, path, reqBody)
	if err != nil {
		return nil, err
	}

	env := new(EnvironmentVariable)
	_, err = s.client.do(ctx, req, env)
	return env, err
}

// DeleteEnv deletes a specific environment variable by its UUID.
func (s *ApplicationsService) DeleteEnv(ctx context.Context, uuid string, envUUID string) error {
	path := fmt.Sprintf("applications/%s/envs/%s", uuid, envUUID)
	req, err := s.client.newRequest(http.MethodDelete, path, nil)
	if err != nil {
		return err
	}

	_, err = s.client.do(ctx, req, nil)
	return err
}

// Storage represents persistent volume configurations attached to an application.
type Storage struct {
	UUID          string `json:"uuid"`
	Name          string `json:"name"`
	MountPath     string `json:"mount_path"`
	HostPath      string `json:"host_path"`
	VolumeName    string `json:"volume_name"`
	ApplicationID int    `json:"application_id"`
}

// ListStorages lists all persistent volume storages attached to the application.
func (s *ApplicationsService) ListStorages(ctx context.Context, uuid string) ([]Storage, error) {
	path := fmt.Sprintf("applications/%s/storages", uuid)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return nil, err
	}

	var storages []Storage
	_, err = s.client.do(ctx, req, &storages)
	return storages, err
}

// ListTasks lists all scheduled tasks created for the application.
func (s *ApplicationsService) ListTasks(ctx context.Context, uuid string) ([]ScheduledTask, error) {
	path := fmt.Sprintf("applications/%s/scheduled-tasks", uuid)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return nil, err
	}

	var tasks []ScheduledTask
	_, err = s.client.do(ctx, req, &tasks)
	return tasks, err
}

// ListTaskExecutions lists task execution records.
func (s *ApplicationsService) ListTaskExecutions(ctx context.Context, uuid string, taskUUID string) ([]ScheduledTaskExecution, error) {
	path := fmt.Sprintf("applications/%s/scheduled-tasks/%s/executions", uuid, taskUUID)
	req, err := s.client.newRequest(http.MethodGet, path, nil)
	if err != nil {
		return nil, err
	}

	var executions []ScheduledTaskExecution
	_, err = s.client.do(ctx, req, &executions)
	return executions, err
}
